spring:
  application:
    name: example
  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:resources.properties
  # db-spring-boot-starter
  jpa:
    hibernate:
      ddl-auto: create # service 啟動時 database 自動建立機制 (create, create-drop, update, validate)
    show-sql: false # 顯示 Sql 語法
    base:
      packages: com.example # Jpa repository package
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      schema-locations: classpath:init/schema.sql
#      data-locations: classpath:init/data.sql

server:
  port: 8080
  servlet:
    context-path: /example

# web-service-spring-boot-starter
web:
  resource:
    pathPattern: /static/** # 靜態資源 Uri
    location: /WEB-INF/static/ # 靜態資源對應目錄，預設是在 /WEB-INF 目錄下
  jsp:
    enable: true # jsp page 開關
    viewNames: jsp/* # jsp 對應 uri
    stuff: .jsp # jsp 副檔名
  thymeleaf:
    enable: true # thymeleaf page 開關
    viewNames: /*, html/*, thymeleaf/* # thymeleaf 對應 uri
    stuff: .html # thymeleaf 副檔名
    templateMode: HTML # thymeleaf 模式
  # web-service-spring-boot-starter
  service:
    uri-mapping: /webservice/* # web service 對應 Uri，http://localhost:8080/{spring.application.name}/webservice?wsdl
    map:
      example:
        beanName: exampleWebServiceImpl # example 資源對應的 bean
        uri-mapping: /example # web service 資源對應 Uri，http://localhost:8080/{spring.application.name}/webservice/example?wsdl